{
  "fileContents": "ZGVmYXVsdFByb2plY3Q6IGRhdGEtZW5naW5lZXJpbmctdGF4aQpkZWZhdWx0RGF0YXNldDogZGF0YWZvcm0KZGVmYXVsdEFzc2VydGlvbkRhdGFzZXQ6IGRhdGFmb3JtX2Fzc2VydGlvbnMKZGVmYXVsdExvY2F0aW9uOiBVUwpkYXRhZm9ybUNvcmVWZXJzaW9uOiAzLjAuMjAK"
}
